In [1]:
import glob
import numpy as np
from PIL import Image

list_classes = [
 'Sony-NEX-7',
 'Motorola-X',
 'HTC-1-M7',
 'Samsung-Galaxy-Note3',
 'Motorola-Droid-Maxx',
 'iPhone-4s',
 'iPhone-6',
 'LG-Nexus-5x',
 'Samsung-Galaxy-S4',
 'Motorola-Nexus-6']

list_dict = {}
for i in range(10):
    key = list_classes[i]
    v = [0,0,0,0,0,0,0,0,0,0]
    v[i] = 1
    list_dict[key] = v
print(list_dict)

train_dir = '../input/train'
test_dir = '../input/test'
test_files = sorted(glob.glob(test_dir+'/*'))
train_files = sorted(glob.glob(train_dir+'/*/*'))
print(test_files[:5])
print(train_files[:5])
print(len(test_files),len(train_files))


def get_img(img_path,crop=112):
    im_array = np.array(Image.open((img_path)), dtype="float32")
    center_x = im_array.shape[1] // 2
    half_crop = crop // 2
    a,b = center_x - half_crop, center_x + half_crop
    return im_array[a:b,a:b,:]

{'Samsung-Galaxy-S4': [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], 'Motorola-X': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 'Samsung-Galaxy-Note3': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 'iPhone-4s': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], 'Sony-NEX-7': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Motorola-Nexus-6': [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], 'Motorola-Droid-Maxx': [0, 0, 0, 0, 1, 0, 0, 0, 0, 0], 'iPhone-6': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], 'HTC-1-M7': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0], 'LG-Nexus-5x': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]}
['../input/test/img_0002a04_manip.tif', '../input/test/img_001e31c_unalt.tif', '../input/test/img_00275cf_manip.tif', '../input/test/img_0034113_unalt.tif', '../input/test/img_00344b7_unalt.tif']
['../input/train/HTC-1-M7/(HTC-1-M7)1.jpg', '../input/train/HTC-1-M7/(HTC-1-M7)10.jpg', '../input/train/HTC-1-M7/(HTC-1-M7)100.jpg', '../input/train/HTC-1-M7/(HTC-1-M7)101.jpg', '../input/train/HTC-1-M7/(HTC-1-M7)102.jpg']
2640 2750


In [2]:
test_p = test_files[0]
print(test_p)
img = get_img(test_p)
print(img)
print(img.shape)

../input/test/img_0002a04_manip.tif
[[[ 206.  201.  189.]
  [ 204.  199.  187.]
  [ 204.  199.  187.]
  ..., 
  [ 207.  202.  190.]
  [ 207.  202.  190.]
  [ 208.  203.  191.]]

 [[ 206.  201.  189.]
  [ 205.  200.  188.]
  [ 206.  201.  189.]
  ..., 
  [ 207.  202.  190.]
  [ 208.  203.  191.]
  [ 207.  202.  190.]]

 [[ 205.  200.  188.]
  [ 204.  199.  187.]
  [ 206.  201.  189.]
  ..., 
  [ 207.  202.  190.]
  [ 208.  203.  191.]
  [ 207.  202.  190.]]

 ..., 
 [[ 207.  202.  188.]
  [ 207.  202.  188.]
  [ 207.  202.  188.]
  ..., 
  [ 209.  202.  191.]
  [ 208.  202.  190.]
  [ 208.  202.  190.]]

 [[ 207.  202.  188.]
  [ 207.  202.  188.]
  [ 207.  202.  188.]
  ..., 
  [ 209.  202.  191.]
  [ 208.  202.  190.]
  [ 208.  202.  190.]]

 [[ 207.  202.  188.]
  [ 207.  202.  188.]
  [ 207.  202.  188.]
  ..., 
  [ 209.  202.  191.]
  [ 208.  202.  190.]
  [ 208.  202.  190.]]]
(112, 112, 3)


In [ ]:
test_p = '../input/train/HTC-1-M7/(HTC-1-M7)1.jpg'
img = get_img(test_p)
print(img)
print(img.shape)

[[[ 171.  145.  120.]
  [ 188.  162.  137.]
  [ 211.  186.  156.]
  ..., 
  [  62.   61.    0.]
  [  87.   82.   26.]
  [ 109.   99.   46.]]

 [[ 196.  170.  145.]
  [ 195.  171.  145.]
  [ 202.  179.  148.]
  ..., 
  [  77.   78.    8.]
  [ 114.  112.   53.]
  [ 116.  111.   56.]]

 [[ 175.  145.  109.]
  [ 182.  152.  116.]
  [ 188.  160.  123.]
  ..., 
  [  94.   96.   21.]
  [  88.   88.   24.]
  [  89.   89.   29.]]

 ..., 
 [[ 183.  142.  110.]
  [ 190.  150.  114.]
  [ 156.  117.   76.]
  ..., 
  [ 106.   80.   31.]
  [ 119.   95.   51.]
  [ 128.  105.   71.]]

 [[ 181.  144.  115.]
  [ 183.  147.  113.]
  [ 146.  108.   71.]
  ..., 
  [ 118.   94.   48.]
  [  70.   48.    9.]
  [ 121.  100.   69.]]

 [[ 178.  143.  113.]
  [ 177.  142.  112.]
  [ 167.  131.   97.]
  ..., 
  [ 109.   88.   41.]
  [  92.   72.   35.]
  [ 161.  144.  114.]]]
(112, 112, 3)


In [ ]:
train_x,train_y = [],[]
test_x = []

for img_p in test_files:
    tmp_x = get_img(img_p,112)
    test_x.append(tmp_x)
print('test done')

cnt = 0
for img_p in train_files:
    tmp_x = get_img(img_p,112)
    tmp_y = img_p.split('/')[-2]
    #tmp_y = list_dict[tmp_y]
    train_x.append(tmp_x)
    #train_y.append(tmp_y)
    cnt += 1
    if cnt % 500 == 0:
        print(cnt)
print('train done')



# train_x = np.array(train_x)
# train_y = np.array(train_y)
# test_x = np.array(test_x)

import pickle
with open('../input/data112.pkl','wb') as fout:
    pickle.dump([train_x,train_y,test_x],fout)
print('done')

test done


In [ ]:
train_x,train_y = [],[]
test_x = []

for img_p in train_files:
    tmp_x = get_img(img_p,224)
    tmp_y = img_p.split('/')[-2]
    #tmp_y = list_dict[tmp_y]
    train_x.append(tmp_x)
    train_y.append(tmp_y)
print('train done')

for img_p in test_files:
    tmp_x = get_img(img_p,224)
    test_x.append(tmp_x)

# train_x = np.array(train_x)
# train_y = np.array(train_y)
# test_x = np.array(test_x)
print('test done')

import pickle
with open('../input/data224.pkl','wb') as fout:
    pickle.dump([train_x,train_y,test_x],fout)
print('done')