In [5]:
import skimage.io
import numpy as np
from PIL import Image
test_p = '/home/jac/Documents/my_github/kaggle_IEEE/input/train/HTC-1-M7/(HTC-1-M7)1.jpg'
img1 = skimage.io.imread(test_p)
print(img1)

[[[120 154 215]
  [125 157 216]
  [129 160 215]
  ..., 
  [116 118 166]
  [118 120 168]
  [121 123 171]]

 [[117 151 212]
  [121 156 214]
  [126 157 212]
  ..., 
  [111 115 162]
  [112 116 163]
  [120 124 171]]

 [[118 154 212]
  [121 156 214]
  [123 156 210]
  ..., 
  [116 123 169]
  [113 121 167]
  [112 120 166]]

 ..., 
 [[139 137 116]
  [138 136 115]
  [136 135 117]
  ..., 
  [ 83  82  87]
  [ 89  87  90]
  [ 84  82  85]]

 [[135 133 112]
  [135 133 112]
  [138 135 118]
  ..., 
  [ 79  78  83]
  [ 80  78  81]
  [ 84  82  83]]

 [[137 135 114]
  [136 134 113]
  [142 139 122]
  ..., 
  [ 75  75  77]
  [ 73  71  74]
  [ 80  78  79]]]


In [6]:
img2 = np.array(Image.open((test_p)), dtype="uint8")
print(img2)

[[[120 154 215]
  [125 157 216]
  [129 160 215]
  ..., 
  [116 118 166]
  [118 120 168]
  [121 123 171]]

 [[117 151 212]
  [121 156 214]
  [126 157 212]
  ..., 
  [111 115 162]
  [112 116 163]
  [120 124 171]]

 [[118 154 212]
  [121 156 214]
  [123 156 210]
  ..., 
  [116 123 169]
  [113 121 167]
  [112 120 166]]

 ..., 
 [[139 137 116]
  [138 136 115]
  [136 135 117]
  ..., 
  [ 83  82  87]
  [ 89  87  90]
  [ 84  82  85]]

 [[135 133 112]
  [135 133 112]
  [138 135 118]
  ..., 
  [ 79  78  83]
  [ 80  78  81]
  [ 84  82  83]]

 [[137 135 114]
  [136 134 113]
  [142 139 122]
  ..., 
  [ 75  75  77]
  [ 73  71  74]
  [ 80  78  79]]]


In [7]:
import scipy.misc
img3 = scipy.misc.imresize(img2, 2.0, interp='bicubic')
print(img3.shape,img2.shape)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  


(5376, 3040, 3) (2688, 1520, 3)
